//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: steammessages_base.proto
namespace SteamKit2
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgProtoBufHeader")]
  public partial class CMsgProtoBufHeader : global::ProtoBuf.IExtensible
  {
    public CMsgProtoBufHeader() {}
    

    private ulong _client_steam_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"client_steam_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong client_steam_id
    {
      get { return _client_steam_id; }
      set { _client_steam_id = value; }
    }

    private int _client_session_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"client_session_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int client_session_id
    {
      get { return _client_session_id; }
      set { _client_session_id = value; }
    }

    private uint _routing_appid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"routing_appid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint routing_appid
    {
      get { return _routing_appid; }
      set { _routing_appid = value; }
    }

    private ulong _job_id_source = (ulong)18446744073709551615;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"job_id_source", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue((ulong)18446744073709551615)]
    public ulong job_id_source
    {
      get { return _job_id_source; }
      set { _job_id_source = value; }
    }

    private ulong _job_id_target = (ulong)18446744073709551615;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"job_id_target", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue((ulong)18446744073709551615)]
    public ulong job_id_target
    {
      get { return _job_id_target; }
      set { _job_id_target = value; }
    }

    private string _target_job_name = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"target_job_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string target_job_name
    {
      get { return _target_job_name; }
      set { _target_job_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgMulti")]
  public partial class CMsgMulti : global::ProtoBuf.IExtensible
  {
    public CMsgMulti() {}
    

    private uint _size_unzipped = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"size_unzipped", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint size_unzipped
    {
      get { return _size_unzipped; }
      set { _size_unzipped = value; }
    }

    private byte[] _message_body = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message_body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(null)]
    public byte[] message_body
    {
      get { return _message_body; }
      set { _message_body = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgAuthTicket")]
  public partial class CMsgAuthTicket : global::ProtoBuf.IExtensible
  {
    public CMsgAuthTicket() {}
    

    private uint _estate = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"estate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint estate
    {
      get { return _estate; }
      set { _estate = value; }
    }

    private uint _eresult = (uint)2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eresult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue((uint)2)]
    public uint eresult
    {
      get { return _eresult; }
      set { _eresult = value; }
    }

    private ulong _steam_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"steam_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }

    private ulong _game_id = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }

    private uint _h_steam_pipe = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"h_steam_pipe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint h_steam_pipe
    {
      get { return _h_steam_pipe; }
      set { _h_steam_pipe = value; }
    }

    private uint _ticket_crc = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ticket_crc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint ticket_crc
    {
      get { return _ticket_crc; }
      set { _ticket_crc = value; }
    }

    private byte[] _ticket = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ticket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(null)]
    public byte[] ticket
    {
      get { return _ticket; }
      set { _ticket = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
#pragma warning restore 1591
