

#pragma warning disable 1591 // this file isn't technically autogenerated, but we don't expect to document every single EMsg

namespace SteamKit2.GC.TF2
{
    public sealed class EGCMsg : EGCMsgBase
    {
        public const uint ReportWarKill = 5001;

        public const uint VoteKickBanPlayer = 5018;
        public const uint VoteKickBanPlayerResult = 5019;
        public const uint KickPlayer = 5020;
        public const uint StartedTraining = 5021;
        public const uint FreeTrial_ChooseMostHelpfulFriend = 5022;
        public const uint RequestTF2Friends = 5023;
        public const uint RequestTF2FriendsResponse = 5024;
        public const uint Replay_UploadedToYouTube = 5025;
        public const uint Replay_SubmitContestEntry = 5026;
        public const uint Replay_SubmitContestEntryResponse = 5027;

        public const uint Coaching_AddToCoaches = 5200;
        public const uint Coaching_AddToCoachesResponse = 5201;
        public const uint Coaching_RemoveFromCoaches = 5202;
        public const uint Coaching_RemoveFromCoachesResponse = 5203;
        public const uint Coaching_FindCoach = 5204;
        public const uint Coaching_FindCoachResponse = 5205;
        public const uint Coaching_AskCoach = 5206;
        public const uint Coaching_AskCoachResponse = 5207;
        public const uint Coaching_CoachJoinGame = 5208;
        public const uint Coaching_CoachJoining = 5209;
        public const uint Coaching_CoachJoined = 5210;
        public const uint Coaching_LikeCurrentCoach = 5211;
        public const uint Coaching_RemoveCurrentCoach = 5212;
        public const uint Coaching_AlreadyRatedCoach = 5213;

        public const uint Duel_Request = 5500;
        public const uint Duel_Response = 5501;
        public const uint Duel_Results = 5502;
        public const uint Duel_Status = 5503;

        public const uint Halloween_ReservedItem = 5600;
        public const uint Halloween_GrantItem = 5601;
        public const uint Halloween_GrantItemResponse = 5604;
        public const uint Halloween_Cheat_QueryResponse = 5605;
        public const uint Halloween_ItemClaimed = 5606;

        public const uint GameServer_LevelInfo = 5700;
        public const uint GameServer_AuthChallenge = 5701;
        public const uint GameServer_AuthChallengeResponse = 5702;
        public const uint GameServer_CreateIdentity = 5703;
        public const uint GameServer_CreateIdentityResponse = 5704;
        public const uint GameServer_List = 5705;
        public const uint GameServer_ListResponse = 5706;
        public const uint GameServer_AuthResult = 5707;
        public const uint GameServer_ResetIdentity = 5708;
        public const uint GameServer_ResetIdentityResponse = 5709;

        public const uint QP_ScoreServers = 5800;
        public const uint QP_ScoreServersResponse = 58001;

        public const uint PickupItemEligibility_Query = 6000;
        public const uint Dev_GrantWarKill = 6001;

        public const uint IncrementKillCountAttribute = 6100;
        public const uint IncrementKillCountResponse = 6101;
    }
}

#pragma warning restore 1591