//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: base_gcmessages.proto
// Note: requires additional types generated from: steammessages.proto
namespace SteamKit2.GC
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOPartyInvite")]
  public partial class CSOPartyInvite : global::ProtoBuf.IExtensible
  {
    public CSOPartyInvite() {}
    

    private ulong _group_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }

    private ulong _sender_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sender_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }

    private string _sender_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sender_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string sender_name
    {
      get { return _sender_name; }
      set { _sender_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOLobbyInvite")]
  public partial class CSOLobbyInvite : global::ProtoBuf.IExtensible
  {
    public CSOLobbyInvite() {}
    

    private ulong _group_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }

    private ulong _sender_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sender_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }

    private string _sender_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sender_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string sender_name
    {
      get { return _sender_name; }
      set { _sender_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgSystemBroadcast")]
  public partial class CMsgSystemBroadcast : global::ProtoBuf.IExtensible
  {
    public CMsgSystemBroadcast() {}
    

    private string _message = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgInviteToParty")]
  public partial class CMsgInviteToParty : global::ProtoBuf.IExtensible
  {
    public CMsgInviteToParty() {}
    

    private ulong _steam_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"steam_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgInvitationCreated")]
  public partial class CMsgInvitationCreated : global::ProtoBuf.IExtensible
  {
    public CMsgInvitationCreated() {}
    

    private ulong _group_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"group_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong group_id
    {
      get { return _group_id; }
      set { _group_id = value; }
    }

    private ulong _steam_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"steam_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgPartyInviteResponse")]
  public partial class CMsgPartyInviteResponse : global::ProtoBuf.IExtensible
  {
    public CMsgPartyInviteResponse() {}
    

    private ulong _party_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"party_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong party_id
    {
      get { return _party_id; }
      set { _party_id = value; }
    }

    private bool _accept = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accept", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool accept
    {
      get { return _accept; }
      set { _accept = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgKickFromParty")]
  public partial class CMsgKickFromParty : global::ProtoBuf.IExtensible
  {
    public CMsgKickFromParty() {}
    

    private ulong _steam_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"steam_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong steam_id
    {
      get { return _steam_id; }
      set { _steam_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgLeaveParty")]
  public partial class CMsgLeaveParty : global::ProtoBuf.IExtensible
  {
    public CMsgLeaveParty() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgServerAddresses")]
  public partial class CMsgServerAddresses : global::ProtoBuf.IExtensible
  {
    public CMsgServerAddresses() {}
    

    private uint _server_public_ip_addr = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"server_public_ip_addr", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint server_public_ip_addr
    {
      get { return _server_public_ip_addr; }
      set { _server_public_ip_addr = value; }
    }

    private uint _server_private_ip_addr = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"server_private_ip_addr", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint server_private_ip_addr
    {
      get { return _server_private_ip_addr; }
      set { _server_private_ip_addr = value; }
    }

    private uint _server_port = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint server_port
    {
      get { return _server_port; }
      set { _server_port = value; }
    }

    private uint _server_tv_port = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"server_tv_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint server_tv_port
    {
      get { return _server_tv_port; }
      set { _server_tv_port = value; }
    }

    private string _server_key = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"server_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string server_key
    {
      get { return _server_key; }
      set { _server_key = value; }
    }

    private bool _server_hibernation = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"server_hibernation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool server_hibernation
    {
      get { return _server_hibernation; }
      set { _server_hibernation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgServerAvailable")]
  public partial class CMsgServerAvailable : global::ProtoBuf.IExtensible
  {
    public CMsgServerAvailable() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOEconGameAccountClient")]
  public partial class CSOEconGameAccountClient : global::ProtoBuf.IExtensible
  {
    public CSOEconGameAccountClient() {}
    

    private uint _additional_backpack_slots = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"additional_backpack_slots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue((uint)0)]
    public uint additional_backpack_slots
    {
      get { return _additional_backpack_slots; }
      set { _additional_backpack_slots = value; }
    }

    private bool _trial_account = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"trial_account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue((bool)false)]
    public bool trial_account
    {
      get { return _trial_account; }
      set { _trial_account = value; }
    }

    private bool _eligible_for_online_play = (bool)true;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"eligible_for_online_play", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue((bool)true)]
    public bool eligible_for_online_play
    {
      get { return _eligible_for_online_play; }
      set { _eligible_for_online_play = value; }
    }

    private bool _need_to_choose_most_helpful_friend = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"need_to_choose_most_helpful_friend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool need_to_choose_most_helpful_friend
    {
      get { return _need_to_choose_most_helpful_friend; }
      set { _need_to_choose_most_helpful_friend = value; }
    }

    private bool _in_coaches_list = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"in_coaches_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool in_coaches_list
    {
      get { return _in_coaches_list; }
      set { _in_coaches_list = value; }
    }

    private uint _trade_ban_expiration = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"trade_ban_expiration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint trade_ban_expiration
    {
      get { return _trade_ban_expiration; }
      set { _trade_ban_expiration = value; }
    }

    private uint _duel_ban_expiration = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"duel_ban_expiration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint duel_ban_expiration
    {
      get { return _duel_ban_expiration; }
      set { _duel_ban_expiration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOItemCriteriaCondition")]
  public partial class CSOItemCriteriaCondition : global::ProtoBuf.IExtensible
  {
    public CSOItemCriteriaCondition() {}
    

    private int _op = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int op
    {
      get { return _op; }
      set { _op = value; }
    }

    private string _field = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string field
    {
      get { return _field; }
      set { _field = value; }
    }

    private bool _required = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"required", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool required
    {
      get { return _required; }
      set { _required = value; }
    }

    private float _float_value = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"float_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(float))]
    public float float_value
    {
      get { return _float_value; }
      set { _float_value = value; }
    }

    private string _string_value = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"string_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string string_value
    {
      get { return _string_value; }
      set { _string_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOItemCriteria")]
  public partial class CSOItemCriteria : global::ProtoBuf.IExtensible
  {
    public CSOItemCriteria() {}
    

    private uint _item_level = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint item_level
    {
      get { return _item_level; }
      set { _item_level = value; }
    }

    private int _item_quality = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int item_quality
    {
      get { return _item_quality; }
      set { _item_quality = value; }
    }

    private bool _item_level_set = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"item_level_set", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool item_level_set
    {
      get { return _item_level_set; }
      set { _item_level_set = value; }
    }

    private bool _item_quality_set = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"item_quality_set", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool item_quality_set
    {
      get { return _item_quality_set; }
      set { _item_quality_set = value; }
    }

    private uint _initial_inventory = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"initial_inventory", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint initial_inventory
    {
      get { return _initial_inventory; }
      set { _initial_inventory = value; }
    }

    private uint _initial_quantity = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"initial_quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint initial_quantity
    {
      get { return _initial_quantity; }
      set { _initial_quantity = value; }
    }

    private bool _forced_quality_match = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"forced_quality_match", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool forced_quality_match
    {
      get { return _forced_quality_match; }
      set { _forced_quality_match = value; }
    }

    private bool _ignore_enabled_flag = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ignore_enabled_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool ignore_enabled_flag
    {
      get { return _ignore_enabled_flag; }
      set { _ignore_enabled_flag = value; }
    }
    private readonly global::System.Collections.Generic.List<CSOItemCriteriaCondition> _conditions = new global::System.Collections.Generic.List<CSOItemCriteriaCondition>();
    [global::ProtoBuf.ProtoMember(9, Name=@"conditions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSOItemCriteriaCondition> conditions
    {
      get { return _conditions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOItemRecipe")]
  public partial class CSOItemRecipe : global::ProtoBuf.IExtensible
  {
    public CSOItemRecipe() {}
    

    private uint _def_index = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"def_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _n_a = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"n_a", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string n_a
    {
      get { return _n_a; }
      set { _n_a = value; }
    }

    private string _desc_inputs = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"desc_inputs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string desc_inputs
    {
      get { return _desc_inputs; }
      set { _desc_inputs = value; }
    }

    private string _desc_outputs = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"desc_outputs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string desc_outputs
    {
      get { return _desc_outputs; }
      set { _desc_outputs = value; }
    }

    private string _di_a = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"di_a", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string di_a
    {
      get { return _di_a; }
      set { _di_a = value; }
    }

    private string _di_b = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"di_b", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string di_b
    {
      get { return _di_b; }
      set { _di_b = value; }
    }

    private string _di_c = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"di_c", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string di_c
    {
      get { return _di_c; }
      set { _di_c = value; }
    }

    private string _do_a = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"do_a", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string do_a
    {
      get { return _do_a; }
      set { _do_a = value; }
    }

    private string _do_b = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"do_b", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string do_b
    {
      get { return _do_b; }
      set { _do_b = value; }
    }

    private string _do_c = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"do_c", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string do_c
    {
      get { return _do_c; }
      set { _do_c = value; }
    }

    private bool _requires_all_same_class = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"requires_all_same_class", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool requires_all_same_class
    {
      get { return _requires_all_same_class; }
      set { _requires_all_same_class = value; }
    }

    private bool _requires_all_same_slot = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"requires_all_same_slot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(default(bool))]
    public bool requires_all_same_slot
    {
      get { return _requires_all_same_slot; }
      set { _requires_all_same_slot = value; }
    }

    private int _class_usage_for_output = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"class_usage_for_output", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int class_usage_for_output
    {
      get { return _class_usage_for_output; }
      set { _class_usage_for_output = value; }
    }

    private int _slot_usage_for_output = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"slot_usage_for_output", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int slot_usage_for_output
    {
      get { return _slot_usage_for_output; }
      set { _slot_usage_for_output = value; }
    }

    private int _set_for_output = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"set_for_output", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int set_for_output
    {
      get { return _set_for_output; }
      set { _set_for_output = value; }
    }
    private readonly global::System.Collections.Generic.List<CSOItemCriteria> _input_items_criteria = new global::System.Collections.Generic.List<CSOItemCriteria>();
    [global::ProtoBuf.ProtoMember(20, Name=@"input_items_criteria", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSOItemCriteria> input_items_criteria
    {
      get { return _input_items_criteria; }
    }
  
    private readonly global::System.Collections.Generic.List<CSOItemCriteria> _output_items_criteria = new global::System.Collections.Generic.List<CSOItemCriteria>();
    [global::ProtoBuf.ProtoMember(21, Name=@"output_items_criteria", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSOItemCriteria> output_items_criteria
    {
      get { return _output_items_criteria; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _input_item_dupe_counts = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(22, Name=@"input_item_dupe_counts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> input_item_dupe_counts
    {
      get { return _input_item_dupe_counts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgDevNewItemRequest")]
  public partial class CMsgDevNewItemRequest : global::ProtoBuf.IExtensible
  {
    public CMsgDevNewItemRequest() {}
    

    private ulong _receiver = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"receiver", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong receiver
    {
      get { return _receiver; }
      set { _receiver = value; }
    }

    private CSOItemCriteria _criteria = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"criteria", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(null)]
    public CSOItemCriteria criteria
    {
      get { return _criteria; }
      set { _criteria = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgIncrementKillCountAttribute")]
  public partial class CMsgIncrementKillCountAttribute : global::ProtoBuf.IExtensible
  {
    public CMsgIncrementKillCountAttribute() {}
    

    private ulong _killer_steam_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"killer_steam_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong killer_steam_id
    {
      get { return _killer_steam_id; }
      set { _killer_steam_id = value; }
    }

    private ulong _victim_steam_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"victim_steam_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong victim_steam_id
    {
      get { return _victim_steam_id; }
      set { _victim_steam_id = value; }
    }

    private ulong _item_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }

    private uint _event_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"event_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint event_type
    {
      get { return _event_type; }
      set { _event_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOEconItemAttribute")]
  public partial class CSOEconItemAttribute : global::ProtoBuf.IExtensible
  {
    public CSOEconItemAttribute() {}
    

    private uint _def_index = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"def_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOEconItem")]
  public partial class CSOEconItem : global::ProtoBuf.IExtensible
  {
    public CSOEconItem() {}
    

    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _account_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _inventory = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"inventory", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint inventory
    {
      get { return _inventory; }
      set { _inventory = value; }
    }

    private uint _def_index = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"def_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private uint _quantity = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }

    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _quality = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }

    private uint _flags = (uint)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue((uint)0)]
    public uint flags
    {
      get { return _flags; }
      set { _flags = value; }
    }

    private uint _origin = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"origin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint origin
    {
      get { return _origin; }
      set { _origin = value; }
    }

    private string _custom_name = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"custom_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string custom_name
    {
      get { return _custom_name; }
      set { _custom_name = value; }
    }

    private string _custom_desc = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"custom_desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string custom_desc
    {
      get { return _custom_desc; }
      set { _custom_desc = value; }
    }
    private readonly global::System.Collections.Generic.List<CSOEconItemAttribute> _attribute = new global::System.Collections.Generic.List<CSOEconItemAttribute>();
    [global::ProtoBuf.ProtoMember(12, Name=@"attribute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSOEconItemAttribute> attribute
    {
      get { return _attribute; }
    }
  

    private CSOEconItem _interior_item = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"interior_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(null)]
    public CSOEconItem interior_item
    {
      get { return _interior_item; }
      set { _interior_item = value; }
    }

    private bool _in_use = (bool)false;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"in_use", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue((bool)false)]
    public bool in_use
    {
      get { return _in_use; }
      set { _in_use = value; }
    }

    private uint _style = (uint)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"style", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue((uint)0)]
    public uint style
    {
      get { return _style; }
      set { _style = value; }
    }

    private ulong _original_id = (ulong)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"original_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue((ulong)0)]
    public ulong original_id
    {
      get { return _original_id; }
      set { _original_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgSortItems")]
  public partial class CMsgSortItems : global::ProtoBuf.IExtensible
  {
    public CMsgSortItems() {}
    

    private uint _sort_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sort_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint sort_type
    {
      get { return _sort_type; }
      set { _sort_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSOEconClaimCode")]
  public partial class CSOEconClaimCode : global::ProtoBuf.IExtensible
  {
    public CSOEconClaimCode() {}
    

    private uint _account_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _code_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"code_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint code_type
    {
      get { return _code_type; }
      set { _code_type = value; }
    }

    private uint _time_acquired = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time_acquired", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint time_acquired
    {
      get { return _time_acquired; }
      set { _time_acquired = value; }
    }

    private string _code = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgStoreGetUserData")]
  public partial class CMsgStoreGetUserData : global::ProtoBuf.IExtensible
  {
    public CMsgStoreGetUserData() {}
    

    private uint _price_sheet_version = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"price_sheet_version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint price_sheet_version
    {
      get { return _price_sheet_version; }
      set { _price_sheet_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgStoreGetUserDataResponse")]
  public partial class CMsgStoreGetUserDataResponse : global::ProtoBuf.IExtensible
  {
    public CMsgStoreGetUserDataResponse() {}
    

    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private int _currency = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"currency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int currency
    {
      get { return _currency; }
      set { _currency = value; }
    }

    private string _country = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"country", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string country
    {
      get { return _country; }
      set { _country = value; }
    }

    private uint _price_sheet_version = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"price_sheet_version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint price_sheet_version
    {
      get { return _price_sheet_version; }
      set { _price_sheet_version = value; }
    }

    private ulong _experiment_data = (ulong)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"experiment_data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue((ulong)0)]
    public ulong experiment_data
    {
      get { return _experiment_data; }
      set { _experiment_data = value; }
    }

    private int _featured_item_idx = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"featured_item_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(int))]
    public int featured_item_idx
    {
      get { return _featured_item_idx; }
      set { _featured_item_idx = value; }
    }

    private bool _show_hat_descriptions = (bool)true;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"show_hat_descriptions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue((bool)true)]
    public bool show_hat_descriptions
    {
      get { return _show_hat_descriptions; }
      set { _show_hat_descriptions = value; }
    }

    private byte[] _price_sheet = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"price_sheet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(null)]
    public byte[] price_sheet
    {
      get { return _price_sheet; }
      set { _price_sheet = value; }
    }

    private int _default_item_sort = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"default_item_sort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue((int)0)]
    public int default_item_sort
    {
      get { return _default_item_sort; }
      set { _default_item_sort = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _popular_items = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"popular_items", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> popular_items
    {
      get { return _popular_items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgUpdateItemSchema")]
  public partial class CMsgUpdateItemSchema : global::ProtoBuf.IExtensible
  {
    public CMsgUpdateItemSchema() {}
    

    private byte[] _items_game = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"items_game", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue(null)]
    public byte[] items_game
    {
      get { return _items_game; }
      set { _items_game = value; }
    }

    private uint _item_schema_version = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_schema_version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint item_schema_version
    {
      get { return _item_schema_version; }
      set { _item_schema_version = value; }
    }

    private string _items_game_url = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"items_game_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string items_game_url
    {
      get { return _items_game_url; }
      set { _items_game_url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRequestItemSchemaData")]
  public partial class CMsgRequestItemSchemaData : global::ProtoBuf.IExtensible
  {
    public CMsgRequestItemSchemaData() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgGCError")]
  public partial class CMsgGCError : global::ProtoBuf.IExtensible
  {
    public CMsgGCError() {}
    

    private string _error_text = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string error_text
    {
      get { return _error_text; }
      set { _error_text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgRequestInventoryRefresh")]
  public partial class CMsgRequestInventoryRefresh : global::ProtoBuf.IExtensible
  {
    public CMsgRequestInventoryRefresh() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgConVarValue")]
  public partial class CMsgConVarValue : global::ProtoBuf.IExtensible
  {
    public CMsgConVarValue() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _value = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::ProtoBuf.ProtoDefaultValue("")]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgReplicateConVars")]
  public partial class CMsgReplicateConVars : global::ProtoBuf.IExtensible
  {
    public CMsgReplicateConVars() {}
    
    private readonly global::System.Collections.Generic.List<CMsgConVarValue> _convars = new global::System.Collections.Generic.List<CMsgConVarValue>();
    [global::ProtoBuf.ProtoMember(1, Name=@"convars", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CMsgConVarValue> convars
    {
      get { return _convars; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgItemAcknowledged")]
  public partial class CMsgItemAcknowledged : global::ProtoBuf.IExtensible
  {
    public CMsgItemAcknowledged() {}
    

    private uint _account_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }

    private uint _inventory = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inventory", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint inventory
    {
      get { return _inventory; }
      set { _inventory = value; }
    }

    private uint _def_index = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"def_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint def_index
    {
      get { return _def_index; }
      set { _def_index = value; }
    }

    private uint _quality = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::ProtoBuf.ProtoDefaultValue(default(uint))]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
#pragma warning restore 1591
