

#pragma warning disable 1591 // this file isn't technically autogenerated, but we don't expect to document every single EMsg

namespace SteamKit2.GC.CSGO
{
    public sealed class EGCMsg
    {
        public const uint StartMatchmakingDeprecated = 9001;
        public const uint StartMatchmakingResponseDeprecated = 9002;
        public const uint ReportRoundEndDeprecated = 9003;
        public const uint StartMatchmaking = 9004;
        public const uint StartMatchmakingResponse = 9005;
        public const uint ReportRoundEnd = 9006;
        public const uint ReportRoundEndLog = 9007;
        public const uint RequestEloBrackets = 9008;
        public const uint RequestEloBracketsResponse = 9009;
        public const uint ClientRequestEloBracket = 9010;
        public const uint ClientRequestEloBracketResponse = 9011;
    }
}

#pragma warning restore 1591