

#pragma warning disable 1591 // this file isn't technically autogenerated, but we don't expect to document every single EMsg

namespace SteamKit2.GC.CSGO
{
    public sealed class EGCMsg : EGCMsgBase
    {
        public const uint RequestEloBracket = 9010;
        public const uint RequestEloBracketResponse = 9011;
    }
}

#pragma warning restore 1591