

#pragma warning disable 1591 // this file isn't technically autogenerated, but we don't expect to document every single EMsg

namespace SteamKit2.GC.Dota
{
    public sealed class EGCMsg : EGCMsgBase
    {
        public const uint JoinChatChannel = 7009;
        public const uint JoinChatChannelResponse = 7010;
        public const uint LeaveChatChannel = 7011;
        public const uint ChatMessage = 7012;
        public const uint OtherJoinedChatChannel = 7013;
        public const uint OtherLeftChatChannel = 7014;

        public const uint RequestPersonaDetails = 7021;
        public const uint PersonaDetails = 7022;

        public const uint GetNews = 7024;
        public const uint NewsResponse = 7025;

        public const uint GetRecentMatches = 7027;
        public const uint RecentMatchesResponse = 7028;

        public const uint FindSourceTVGames = 7031;
        public const uint SourceTVGamesResponse = 7032;
        public const uint StartFindingMatch = 7033;
        public const uint AbandonCurrentGame = 7035;
        public const uint StopFindingMatch = 7036;

        public const uint ForceSOCacheResend = 7037;

        public const uint PracticeLobbyCreate = 7038;
        public const uint PracticeLobbyLeave = 7040;
        public const uint PracticeLobbyLaunch = 7041;
        public const uint PracticeLobbyList = 7042;
        public const uint PracticeLobbyListResponse = 7043;
        public const uint PracticeLobbyJoin = 7044;
        public const uint SetAvatar = 7045;
        public const uint PracticeLobbySetDetails = 7046;
        public const uint PracticeLobbySetTeamSlot = 7047;

        public const uint InitialQuestionnaireResponse = 7049;

        public const uint TournamentRequest = 7051;
        public const uint TournamentResponse = 7052;

        public const uint SetTeamSlot = 7054;
        public const uint SetTeamSlotResponse = 7055;

        public const uint BroadcastNotification = 7056;
        public const uint RequestDefaultChatChannel = 7058;
        public const uint RequestDefaultChatChannelResponse = 7059;
        public const uint RequestChatChannelList = 7060;
        public const uint RequestChatChannelListResponse = 7061;
        public const uint TodayMessages = 7062;
        public const uint RequestTodayMessages = 7063;
        public const uint RequestMatches = 7064;
        public const uint RequestMatchesResponse = 7065;
        public const uint MatchmakingSearchCountRequest = 7066;
        public const uint MatchmakingSearchCountResponse = 7067;

        public const uint ReadyUp = 7070;
        public const uint KickedFromMatchmakingQueue = 7071;

        public const uint SpectateFriendGame = 7073;
        public const uint SpectateFriendGameResponse = 7074;

        public const uint ReportsRemainingRequest = 7076;
        public const uint ReportsRemainingResponse = 7077;
        public const uint SubmitPlayerReport = 7078;
        public const uint SubmitPlayerReportResponse = 7079;

        public const uint PracticeLobbyKick = 7081;

        public const uint RequestSaveGames = 7084;
        public const uint RequestSaveGamesResponse = 7086;

        public const uint WatchGame = 7091;
        public const uint WatchGameResponse = 7092;

        public const uint MatchDetailsRequest = 7095;
        public const uint MatchDetailsResponse = 7096;

        public const uint CancelWatchGame = 7097;

        public const uint ProfileRequest = 7098;
        public const uint ProfileResponse = 7099;

        public const uint Popup = 7102;
        public const uint NotifySuccessfulReport = 7103;
        public const uint ClearNotifySuccessfulReport = 7104;

        public const uint TransferTeamAdmin = 7107; // this may be totally wrong
        public const uint TransferTeamAdminResponse = 7108; // possibly DotaGenericResult?

        public const uint MatchGroupWaitTimesRequest = 7109;
        public const uint MatchGroupWaitTimesResponse = 7110;

        public const uint FriendPracticeLobbyListRequest = 7111;
        public const uint FriendPracticeLobbyListResponse = 7112;
        public const uint FriendPracticeLobbyJoinResponse = 7113;

        public const uint CreateTeam = 7115;
        public const uint CreateTeamResponse = 7116;
        public const uint DisbandTeam = 7117;
        public const uint DisbandTeamResponse = 7118;
        public const uint RequestTeamData = 7119;
        public const uint RequestTeamDataResponse = 7120;
        public const uint TeamData = 7121;
        public const uint InitiateTeamInvite = 7122;
        public const uint InitiateTeamInviteResponse = 7123;
        public const uint TeamInvite = 7124;
        public const uint TeamInviteReply = 7125;
        public const uint TeamInviteReplyResponse = 7126;
        public const uint KickTeamMember = 7128;
        public const uint KickTeamMemberResponse = 7129;
        public const uint LeaveTeam = 7130;
        public const uint LeaveTeamResponse = 7131;
        public const uint SuggestTeamMatchmaking = 7132;

        public const uint HeroFavoritesAdd = 7133;
        public const uint HeroFavoritesRemove = 7134;
        public const uint PlayerHeroesRecentRequest = 7135;
        public const uint PlayerHeroesRecent = 7136;

        public const uint SetChatChannelVerbosity = 7137;
        public const uint ChatChannelFullUpdate = 7138;

        public const uint EditTeamLogo = 7139;
        public const uint EditTeamLogoResponse = 7140;

        public const uint RequestLeaguesWithLiveGames = 7147;
        public const uint LeaguesWithLiveGamesResponse = 7148;

        public const uint MatchVote = 7152;
        public const uint MatchVoteResponse = 7153;

        public const uint RetrieveMatchVote = 7154;
        public const uint RetrieveMatchVoteResponse = 7155;

        public const uint CheckSpectatorOnly = 7162;
        public const uint CheckSpectatorOnlyResponse = 7163;

    }
}

#pragma warning restore 1591