//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classless.Hasher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Classless.Hasher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HashAlgorithm cannot be changed in the middle of a hash computation..
        /// </summary>
        internal static string cantChangeHasher {
            get {
                return ResourceManager.GetString("cantChangeHasher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The List of HashAlgorithms cannot be changed in the middle of a hash computation..
        /// </summary>
        internal static string cantChangeHasherList {
            get {
                return ResourceManager.GetString("cantChangeHasherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key cannot be changed in the middle of a hash computation..
        /// </summary>
        internal static string cantChangeKey {
            get {
                return ResourceManager.GetString("cantChangeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HashAlgorithm cannot be null..
        /// </summary>
        internal static string hashCantBeNull {
            get {
                return ResourceManager.GetString("hashCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HashAlgorithmList cannot be null..
        /// </summary>
        internal static string hashListCantBeNull {
            get {
                return ResourceManager.GetString("hashListCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index specified was out of range..
        /// </summary>
        internal static string indexOutOfRange {
            get {
                return ResourceManager.GetString("indexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Block Size must be greater than 0..
        /// </summary>
        internal static string invalidBlockSize {
            get {
                return ResourceManager.GetString("invalidBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CRC Order must represent full bytes and be between 8 and 64..
        /// </summary>
        internal static string invalidCrcOrder {
            get {
                return ResourceManager.GetString("invalidCrcOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FletcherOrder can only be 8, 16, or 32 bits long..
        /// </summary>
        internal static string invalidFletcherOrder {
            get {
                return ResourceManager.GetString("invalidFletcherOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FNV Order can only be 32 or 64 bits long..
        /// </summary>
        internal static string invalidFnvOrder {
            get {
                return ResourceManager.GetString("invalidFnvOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HashChain must initialize at least one iteration..
        /// </summary>
        internal static string invalidHashChainInit {
            get {
                return ResourceManager.GetString("invalidHashChainInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HAVAL Length can only be 128, 160, 192, 224, or 256 bits long..
        /// </summary>
        internal static string invalidHavalLength {
            get {
                return ResourceManager.GetString("invalidHavalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of HAVAL Passes can only be 3, 4, or 5..
        /// </summary>
        internal static string invalidHavalPasses {
            get {
                return ResourceManager.GetString("invalidHavalPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Range properties of a Node cannot be less than 0..
        /// </summary>
        internal static string invalidNodeRange {
            get {
                return ResourceManager.GetString("invalidNodeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Snefru2 Length can only be 128 or 256 bits long..
        /// </summary>
        internal static string invalidSnefruLength {
            get {
                return ResourceManager.GetString("invalidSnefruLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Snefru2 Passes can only be 4 or 8..
        /// </summary>
        internal static string invalidSnefruPasses {
            get {
                return ResourceManager.GetString("invalidSnefruPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sum Order must represent full bytes and be between 8 and 64..
        /// </summary>
        internal static string invalidSumOrder {
            get {
                return ResourceManager.GetString("invalidSumOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tiger Length can only be 128, 160, or 192 bits long..
        /// </summary>
        internal static string invalidTigerLength {
            get {
                return ResourceManager.GetString("invalidTigerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of bytes to convert must be a multiple of the size of the type..
        /// </summary>
        internal static string lengthMultipleOfTypeSize {
            get {
                return ResourceManager.GetString("lengthMultipleOfTypeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length and offset provided extend past the end of the array..
        /// </summary>
        internal static string lengthOffsetOutOfBounds {
            get {
                return ResourceManager.GetString("lengthOffsetOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Length specified is larger than this implementation allows..
        /// </summary>
        internal static string lengthWayTooLong {
            get {
                return ResourceManager.GetString("lengthWayTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes cannot have more than one relationship between each other..
        /// </summary>
        internal static string nodeCantLoop {
            get {
                return ResourceManager.GetString("nodeCantLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A HashAlgorithm cannot be placed in the collection more than once..
        /// </summary>
        internal static string noDupeHashers {
            get {
                return ResourceManager.GetString("noDupeHashers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hash Parameters cannot be null..
        /// </summary>
        internal static string paramCantBeNull {
            get {
                return ResourceManager.GetString("paramCantBeNull", resourceCulture);
            }
        }
    }
}
