name: Build ProtobufDumper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish Resources/ProtobufDumper/ProtobufDumper/ProtobufDumper.csproj -c Release -r win-x64 --self-contained false -o out

      - uses: actions/upload-artifact@v4
        with:
          name: ProtobufDumper
          path: out/
